# Generated by Django 5.2.9 on 2026-02-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('charging_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='stations.chargingpoint')),
            ],
        ),
    ]
