# Generated by Django 5.2.9 on 2026-02-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='is_available',
        ),
    ]
