# Generated by Django 5.2.9 on 2026-02-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_slot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
