# Generated by Django 5.2.9 on 2026-02-03 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_alter_slot_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='slot',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
