# Generated by Django 5.2.9 on 2026-02-01 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(default='', max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(blank=True, limit_choices_to={'role': 'operator'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.CharField(max_length=50)),
                ('connector_type', models.CharField(choices=[('type2', 'Type 2'), ('ccs', 'CCS'), ('chademo', 'CHAdeMO')], default='type2', max_length=20)),
                ('power_kw', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_points', to='stations.chargingstation')),
            ],
        ),
    ]
