# Generated by Django 5.2.9 on 2026-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
